server:
  port: 8781
  spring:
    application:
      name: openfeign-server
  eureka:
    client:
      register-with-eureka: true
      fetch-registry: false
      service-url:
        defaultZone: http://localhost:8761/eureka/